### ISSUE TITLE
Laravel 6.0 Compatibility

### ISSUE THREAD

**Issue by nasatome** [Xethron/migrations-generator#191]
Laravel 6.0 Compatibility ?

`composer require --dev "xethron/migrations-generator"`

```
Using version ^2.0 for xethron/migrations-generator
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - xethron/migrations-generator v2.0.0 requires way/generators dev-feature/laravel-five-stable -> no matching package found.
    - Conclusion: remove laravel/framework v6.0.0
    - Conclusion: don't install laravel/framework v6.0.0
    - xethron/migrations-generator v2.0.1 requires xethron/laravel-4-generators ~3.1.0 -> satisfiable by xethron/laravel-4-generators[3.1.0, 3.1.1].
    - xethron/migrations-generator v2.0.2 requires xethron/laravel-4-generators ~3.1.0 -> satisfiable by xethron/laravel-4-generators[3.1.0, 3.1.1].
```

**Comment by jasperf** [comment]
Perhaps https://github.com/laracasts/Laravel-5-Generators-Extended will be a good alternative.

**Comment by blindiceyes** [comment]
will be waiting for update. thanks for this

**Comment by jdamps** [comment]
have the same problem today,
I just have installed laravel in supported version and now it is working.
composer create-project laravel/laravel="5.6.*" Project_Name

**Comment by MammutAlex** [comment]
> Perhaps https://github.com/laracasts/Laravel-5-Generators-Extended will be a good alternative.

This is not an alternative

**Comment by jasperf** [comment]
Did some more research yesterday @MammutAlex . Though Laravel 5 Generators Extended is not a true replacement it does make migrations much easier as you can add columns and column types to commands to generate your migrations that much faster. There is a Laracasts Video on it too, but cannot locate it now. 

However if you need to convert a database to migrations I did find a [Sequel Pro extension](https://github.com/cviebrock/sequel-pro-laravel-export). Perhaps there is one for MySQL Workbench too.

**Comment by jase-languasco** [comment]
@jasperf +1 to the Sequel Pro extension. I just used it on 400 + tables and it worked well.

**Comment by jasperf** [comment]
@jase-languasco Good to hear it worked well for you too man.

**Comment by Bagadulittle** [comment]
@bernhard: You´ve done a realy good job!
Will you make it compatible for laravel 6? 
or is there a way to install it anyway?
For me it is no option to install laravel in Required Version. I Need Laravel6. ;)
I think the problem is that your code depends on jeffry´s old laravel-4-generator not the [https://github.com/laracasts/Laravel-5-Generators-Extended](https://github.com/laracasts/Laravel-5-Generators-Extended)
thnx

**Comment by Xethron** [comment]
@Bagadulittle Yes, that seems to be the problem. Will require some work to get it working with 6 I think.

For now, the best workaround is to install a fresh copy of Laravel 5.*, generate the migrations, and copy them across.

**Comment by Bagadulittle** [comment]
@Xethron: thanks that´s what i do at the moment. And that´s a little laborious, But i allways think abougth to r3write the hole thing. If i do this i get you in touch. thanX for your reply.

**Comment by vahidalvandi** [comment]
please add support laravel 6

**Comment by leonelhrp** [comment]
pleaseee @vahidalvandi

**Comment by vahidalvandi** [comment]
i found new solution with EER model and mysql workbench 8 
https://www.aparat.com/v/boFdX

**Comment by johncarlson21** [comment]
It does slightly work with new version of of WB 8 but just lets you preview where you can copy/paste a large amount of data and split it

**Comment by oscarafdev** [comment]
Use https://github.com/oscarafdev/migrations-generator

**Comment by danangs57** [comment]
> Use https://github.com/oscarafdev/migrations-generator
in 6*2 still has error

**Comment by trentramseyer** [comment]
> 
> 
> > Use https://github.com/oscarafdev/migrations-generator
> > in 6*2 still has error

If you get the camel_case error just change the lines to this 

               $converted = Str::camel($this->migrationName);

		return [
			'CLASS' => ucwords($converted),
			'UP'    => $up,
			'DOWN'  => $down
		];

**Comment by oscarafdev** [comment]
> > Use https://github.com/oscarafdev/migrations-generator
> > in 6*2 still has error

Fixed, ty

**Comment by hose1021** [comment]
> > > Use https://github.com/oscarafdev/migrations-generator
> > > in 6*2 still has error
> 
> Fixed, ty

![image](https://user-images.githubusercontent.com/30587167/70711351-c6be8d80-1cfa-11ea-9664-9c91790f537f.png)

**Comment by Mr-Fadul** [comment]
camel_case error not fixed, how to fix? 

edit: fixed but composer dont download the most recent fix, edit to this.

return [
			'CLASS' => ucwords(\Str::camel($this->migrationName)),
			'UP'    => $up,
			'DOWN'  => $down
		];

**Comment by oscarafdev** [comment]
> camel_case error not fixed, how to fix?
> 
> edit: fixed but composer dont download the most recent fix, edit to this.
> 
> return [
> 'CLASS' => ucwords(\Str::camel($this->migrationName)),
> 'UP' => $up,
> 'DOWN' => $down
> ];


Sorry, I forgot to create a new release

**Comment by EVNIKHIL** [comment]
> 'CLASS' => ucwords(\Str::camel($this->migrationName)),

Please change '\Str' to 'Str' if you have used the 'use Illuminate\Support\Str;' on top. I got an error

**Comment by eranamarante** [comment]
> Use https://github.com/oscarafdev/migrations-generator

I get this error upon executing "composer require oscarafdev/migrations-generator 2.0.16"
_Your requirements could not be resolved to an installable set of packages._

Sorry still a newbie in laravel :(

**Comment by kitloong** [comment]
I have updated the package with more data type supports such as `json`, `set`, spatial type like `geometry`, `point`, and fixed some issues.

It also support Laravel from `5.6` to `7.0`

Please try https://github.com/kitloong/laravel-migrations-generator and comment

**Comment by vladislavtkachenko** [comment]
> I have updated the package with more data type supports such as `json`, `set`, spatial type like `geometry`, `point`, and fixed some issues.
> 
> It also support Laravel from `5.6` to `7.0`
> 
> Please try https://github.com/kitloong/laravel-migrations-generator and comment

It works on Laravel 7.4.0 & php 7.4.3

**Comment by ssmusoke** [comment]
@kitloong is it possible to force the migrations to be regenerated, when I run it twice I get two sets of migrations. 

Thanks by the way for making this Laravel 6 and 7 compatible

**Comment by kitloong** [comment]
@ssmusoke Thank you.
Currently there is no way to merge new generated migrations with existing.
You need to delete the old set before generate new migrations.
